export const ACTION_TYPE = {
    SET_USER: "SET_USER",
    LOGOUT: "LOGOUT",
    SET_POST_DATA: "SET_POST_DATA",
    LOAD_POST_ASYNC: "LOAD_POST_ASYNC",
    ADD_COMMENT_ASYNC: "ADD_COMMENT_ASYNC",
    REMOVE_COMMENT_ASYNC: "REMOVE_COMMENT_ASYNC",
    CLOSE_MODAL: "CLOSE_MODAL",
    OPEN_MODAL: "OPEN_MODAL",
    SAVE_POST_ASYNC: "SAVE_POST_ASYNC",
    RESET_POST_DATA: "RESET_POST_DATA",
    ADD_COMMENT: "ADD_COMMENT",
    REMOVE_COMMENT: "REMOVE_COMMENT",
};
